
clone:
	@echo TODO
	exit 1

	git clone https://github.com/gd-arnold/tiny-nginx --progress --depth 1
	git clone https://github.com/nginx/nginx --progress --branch=release-1.31.4 --depth 1
	git clone https://github.com/haproxy/haproxy --progress --branch=v3.4.0 --depth 1
